change to threading as aiohttp does not async post (#123)
tier4/GSM8Signage pull request #127
Opened 2024-09-30 05:55 UTC by tkhmy

* change to threading as aiohttp does not async post

* add back aiohttp

* uncommon debug

---------

## Related Issue(required)

## Description(required)

## Review Procedure(required)

## Related PR(optional)

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Read [commit-guidelines][commit-guidelines]
- [ ] Assign PR to reviewer

If you are adding new package following items are required:

- [ ] Documentation with description of the package is available
- [ ] A sample launch file and parameter file are available if the package contains executable nodes

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write release notes

[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

2024-09-30 05:56 UTC, tkhmy commented
@yabuta ansible も aiohttp を追加が必要です。

2024-10-02 10:38 UTC, yabuta requested changes

2024-10-02 10:38 UTC, yabuta commented on src/signage/src/signage/route_handler.py
> +                    data = await response.json()
この下の
```
data = json.loads(respond.text)
```
は不要かと思います

2024-10-03 00:10 UTC, tkhmy commented on src/signage/src/signage/route_handler.py
> +                    data = await response.json()
修正しました。

2024-10-03 00:47 UTC, yabuta approved these changes
LGTM

2024-10-03 00:52 UTC, merged